#!/usr/bin/env python3
# plot_test_only.py
#
# What it does (NEW routines compatible):
#   - Loads runs_mlp_v10/best_model.py and its checkpoint (from run_mlp.py).
#   - Uses ONLY the TEST split saved in the checkpoint.
#   - Normalizes inputs exactly like training via best_model.normalize_inputs().
#   - Runs inference -> predictions in *scaled log space*.
#   - (Optionally) clamps scaled preds to [-1, 0] before denormalizing (to keep linear values in [1e-30, 1]).
#   - Denormalizes to linear space with best_model.denormalize_targets().
#   - Reports MSE in BOTH spaces and prints diagnostics.
#   - Plots Pred vs True in linear space with log-log axes.
#
# Notes re: electron:
#   - In the current training pipeline, `abund_e-_dex` **is included** among the input features (like other abundances).
#   - Whether an `e-` species **target** exists depends on your CSV column names:
#       * If your species columns are still generic (species_###), there is no named `e-` target.
#       * If you regenerated/renamed the species columns to real symbols, and one is `e-`, it will be included if present in TARGET_COLS.

import os
import importlib.util
import logging
from typing import List, Tuple

import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

plt.style.use('science.mplstyle')

# =============================================================================
# GLOBAL SETTINGS
# =============================================================================
# Path to the CSV used during training
CSV_PATH: str = '/Users/yashnilmohanty/Desktop/chemCalculations/NEW_VERS/all_gas_v10_no_stripe_clean.csv'

BEST_MODULE: str = os.path.join("runs_mlp_NEW_VERS", "best_model.py")
OUT_PNG: str = os.path.join("runs_mlp_NEW_VERS", "pred_vs_true_test.png")

# Use log10 axes on the linear-space scatter
LOG10_AXES: bool = True

# Clamp scaled predictions to [-1, 0] before denorm (evaluation-time only)
CLAMP_SCALED_BEFORE_DENORM: bool = True
CLAMP_MIN_SCALED: float = -1.0
CLAMP_MAX_SCALED: float = 0.0

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-7s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("plot_test")

# =============================================================================
# Helpers
# =============================================================================
def fmt(x) -> str:
    try:
        return f"{float(x):.3e}"
    except Exception:
        return str(x)

def load_module_from_path(path: str):
    path = os.path.abspath(path)
    name = os.path.splitext(os.path.basename(path))[0]
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load module from {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

def targets_to_scaled(y_linear: np.ndarray, zero_floor: float, log_eps: float, log_scale: float) -> np.ndarray:
    """
    Training transform for targets:
      1) (x < zero_floor) -> 0
      2) log10(max(x, log_eps))
      3) divide by log_scale (30)
    """
    y = y_linear.copy()
    y[y < zero_floor] = 0.0
    y = np.log10(np.maximum(y, log_eps))
    y /= log_scale
    return y

# =============================================================================
# Main
# =============================================================================
def main():
    # Load best_model + model
    best_mod = load_module_from_path(BEST_MODULE)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    log.info("Device: %s", device.type)

    # Show normalization rules (traceability) — reflect the new pipeline
    input_cols = getattr(best_mod, "INPUT_COLS", [])
    log.info("USING NORMALIZATION — INPUTS")
    log.info("  - T_K: x / %s", fmt(best_mod.TEMP_DIVISOR))
    log.info("  - P_bar: log10(safe(x)) / %s", fmt(best_mod.INPUT_LOG_SCALE))
    if "fZ_dex" in input_cols:
        log.info("  - fZ_dex: x / %s", fmt(best_mod.INPUT_LOG_SCALE))
    if "fZ" in input_cols:
        log.info("  - fZ: log10(safe(x)) / %s", fmt(best_mod.INPUT_LOG_SCALE))
    # These exist in best_model.py generated by run_mlp_grid.py
    if hasattr(best_mod, "ABUND_EPSILON_OFFSET") and hasattr(best_mod, "ABUND_DEX_SCALE"):
        log.info("  - abund_*_dex (including abund_e-_dex): (epsilon - %.1f) / %.0f",
                 float(best_mod.ABUND_EPSILON_OFFSET), float(best_mod.ABUND_DEX_SCALE))

    log.info("USING NORMALIZATION — TARGETS")
    log.info("  rule: (x < %s) -> 0, then log10(all), then x / %s",
             fmt(best_mod.TARGET_ZERO_FLOOR), fmt(best_mod.TARGET_LOG_SCALE))
    log.info("  LOG_EPS: %s (for safe log10)", fmt(best_mod.LOG_EPS))

    model = best_mod.load_model(device=device)

    # Load CSV
    csv_path = os.path.abspath(CSV_PATH)
    log.info("Loading CSV: %s", csv_path)
    df = pd.read_csv(csv_path)
    log.info("Loaded shape: %s rows x %s cols", df.shape[0], df.shape[1])

    # Pull metadata from checkpoint
    ckpt = torch.load(best_mod.CHECKPOINT_PATH, map_location="cpu")
    cfg = ckpt.get("config", {})
    target_cols = cfg.get("target_cols", getattr(best_mod, "TARGET_COLS", None))
    splits = cfg.get("splits", None)

    if target_cols is None:
        # Fallback (shouldn't happen; best_model.py carries TARGET_COLS)
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        drop_from_targets = ["group_index", "point_index"]
        target_cols = [c for c in numeric_cols if c not in input_cols and c not in drop_from_targets]
        log.warning("Falling back to derived target_cols. Count=%d", len(target_cols))
    else:
        log.info("Loaded target_cols from checkpoint/module. Count=%d", len(target_cols))

    # Tell user whether 'e-' is actually a named target
    if any(c.strip() == "e-" for c in target_cols):
        log.info("Target set includes 'e-' (electron number density).")
    else:
        log.info("Target set does NOT include a named 'e-' column. "
                 "If you want it, rename species_### columns to true symbols before training.")

    # Use ONLY the TEST split saved during training
    if splits is None or "test_idx" not in splits:
        raise RuntimeError(
            "Checkpoint does not contain saved splits with a test set. "
            "Re-train with run_mlp_grid.py that records splits."
        )
    test_idx = np.asarray(splits["test_idx"], dtype=int)
    df_test = df.iloc[test_idx].copy()
    n_rows = len(df_test)
    n_tgts = len(target_cols)

    log.info("Using TEST split only: rows=%d (of %d total)", n_rows, len(df))

    # Normalize inputs (exact training transform)
    X_norm = best_mod.normalize_inputs(df_test).to(device)

    # Inference -> scaled predictions (training space)
    # ----------------------------
    # TIMING OPTIONS
    # ----------------------------
    # TIME_EACH_SAMPLE=False -> time whole batch (recommended)
    # TIME_EACH_SAMPLE=True  -> run forward per sample (slow; measures per-sample overhead)
    TIME_EACH_SAMPLE = False

    def _synchronize_if_cuda():
        if device.type == "cuda":
            torch.cuda.synchronize()

    # Inference timing
    import time
    n_samples = X_norm.shape[0]

    # --- Batch timing (recommended) ---
    _synchronize_if_cuda()
    t0 = time.perf_counter()
    with torch.no_grad():
        y_scaled_pred_tensor = model(X_norm)
    _synchronize_if_cuda()
    t1 = time.perf_counter()
    batch_time = t1 - t0
    try:
        y_scaled_pred = y_scaled_pred_tensor.cpu().numpy().astype(np.float64)
    except Exception:
        # fallback if model already returned numpy
        y_scaled_pred = np.asarray(y_scaled_pred_tensor, dtype=np.float64)

    avg_per_sample = batch_time / float(max(1, n_samples))

    log.info("Inference timing (batch): total=%.6f s | avg/sample=%.6f s | samples=%d",
             batch_time, avg_per_sample, n_samples)

    # --- Optional: true per-sample timing (expensive) ---
    per_sample_times = None
    if TIME_EACH_SAMPLE:
        log.info("Timing each sample individually (this will be much slower)...")
        per_sample_times = np.empty(n_samples, dtype=np.float64)
        with torch.no_grad():
            for i in range(n_samples):
                xi = X_norm[i : i + 1]  # keep batch dim
                _synchronize_if_cuda()
                t0 = time.perf_counter()
                out_i = model(xi)
                _synchronize_if_cuda()
                t1 = time.perf_counter()
                per_sample_times[i] = t1 - t0
        # ensure shapes and values
        per_total = float(per_sample_times.sum())
        per_mean = float(per_sample_times.mean())
        per_median = float(np.median(per_sample_times))
        per_std = float(per_sample_times.std())
        log.info("Per-sample timing (loop): total=%.6f s | mean=%.6f s | median=%.6f s | std=%.6f s",
                 per_total, per_mean, per_median, per_std)

    # True targets in both spaces
    y_true_linear = df_test[target_cols].to_numpy(dtype=np.float64)
    y_scaled_true = targets_to_scaled(
        y_true_linear,
        zero_floor=float(best_mod.TARGET_ZERO_FLOOR),
        log_eps=float(best_mod.LOG_EPS),
        log_scale=float(best_mod.TARGET_LOG_SCALE),
    )

    # MSE in scaled (training) space
    mse_scaled = float(np.mean((y_scaled_pred - y_scaled_true) ** 2))

    # Optionally clamp in scaled space before denorm to avoid explosive linear MSE
    if CLAMP_SCALED_BEFORE_DENORM:
        y_scaled_for_denorm = np.clip(y_scaled_pred, CLAMP_MIN_SCALED, CLAMP_MAX_SCALED)
        log.info("Clamping scaled predictions to [%.1f, %.1f] before denorm.", CLAMP_MIN_SCALED, CLAMP_MAX_SCALED)
    else:
        y_scaled_for_denorm = y_scaled_pred
        log.info("NO clamping before denorm (preds may exceed [10^-30, 1] in linear space).")

    # Denormalize predictions to linear space
    y_pred_linear = best_mod.denormalize_targets(y_scaled_for_denorm).astype(np.float64)

    # Floor true targets to 0 the same way (before logging step)
    y_true_linear_floor = y_true_linear.copy()
    y_true_linear_floor[y_true_linear_floor < float(best_mod.TARGET_ZERO_FLOOR)] = 0.0

    # MSE in linear space
    mse_linear = float(np.mean((y_pred_linear - y_true_linear_floor) ** 2))

    # ==============================
    # Diagnostics
    # ==============================
    y_pred_flat = y_pred_linear.reshape(-1)
    y_true_flat = y_true_linear_floor.reshape(-1)

    over1 = int(np.sum(y_pred_flat > 1.0))
    under_floor = int(np.sum(y_pred_flat < 1e-30))
    q_pred = np.quantile(np.log10(np.clip(y_pred_flat, 1e-300, None)), [0.5, 0.9, 0.99, 0.999])

    vals_true_log = np.round(np.log10(np.clip(y_true_flat, 1e-300, None)), 3)
    uniq, cnt = np.unique(vals_true_log, return_counts=True)
    top = sorted(zip(uniq, cnt), key=lambda t: -t[1])[:10]
    around_1e_2 = int(np.sum(np.isclose(vals_true_log, -2.000, atol=0.0005)))

    log.info("Sample size (TEST): rows=%d, targets=%d, total points=%d", n_rows, n_tgts, n_rows * n_tgts)
    log.info("MSE (scaled training space): %s", fmt(mse_scaled))
    log.info("MSE (linear space)         : %s", fmt(mse_linear))
    log.info("Diagnostics — predictions (linear): >1 count=%d | <1e-30 count=%d", over1, under_floor)
    log.info("Diagnostics — log10(pred) quantiles [50%%,90%%,99%%,99.9%%]: %s", np.array2string(q_pred, precision=3))
    log.info("Diagnostics — most common log10(true) values (value,count): %s", top)
    log.info("Diagnostics — count near true≈1e-2 (vertical band): %d", around_1e_2)

    # ==============================
    # Plot (linear space)
    # ==============================
    if LOG10_AXES:
        mask = (y_true_flat > 0.0) & (y_pred_flat > 0.0)
        x_plot = y_true_flat[mask]
        y_plot = y_pred_flat[mask]
    else:
        x_plot = y_true_flat
        y_plot = y_pred_flat

    # Limits for y=x reference line
    if x_plot.size and y_plot.size:
        vmin = float(min(x_plot.min(), y_plot.min()))
        vmax = float(max(x_plot.max(), y_plot.max()))
    else:
        vmin, vmax = 1e-30, 1.0
    if not np.isfinite(vmin): vmin = 1e-30
    if not np.isfinite(vmax) or vmax <= vmin: vmax = vmin * 10.0

    plt.figure(figsize=(7.5, 7.0))
    plt.scatter(x_plot, y_plot, s=8, alpha=0.6)
    plt.plot([vmin, vmax], [vmin, vmax], linewidth=3.0, zorder=10, color="black")
    plt.xlabel("Fastchem Abundance")
    plt.ylabel("Predicted Abundance")

    clamped_flag = " (CLAMPED)" if CLAMP_SCALED_BEFORE_DENORM else ""
    #title_lines = [
    #    f"Predicted vs True — TEST set ({n_rows} rows) × {n_tgts} targets",
    #    f"MSE_scaled={fmt(mse_scaled)} | MSE_linear={fmt(mse_linear)}{clamped_flag}",
    #]
    #plt.title("\n".join(title_lines))

    if LOG10_AXES and x_plot.size:
        plt.xscale("log")
        plt.yscale("log")
        plt.xlim(1e-30, 1)
        plt.ylim(1e-30, 1)

    plt.tight_layout()
    out_path = os.path.abspath(OUT_PNG)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    plt.savefig(out_path, dpi=200)
    log.info("Saved plot: %s", out_path)

if __name__ == "__main__":
    main()
