#!/usr/bin/env python3
# Auto-generated by run_mlp_grid.py at 2025-10-25 14:42:56
# Reconstructs the plain MLP and loads weights. Forward returns FULL-SIZE SCALED TARGETS.

import numpy as np
import torch
from torch import nn

INPUT_COLS = ['T_K', 'P_bar', 'abund_C_dex', 'abund_H_dex', 'abund_N_dex', 'abund_O_dex', 'abund_S_dex']
TARGET_COLS = ['e-', 'comp_S', 'comp_O', 'comp_H', 'comp_N', 'comp_C', 'N2', 'O2', 'H2', 'S2', 'C5', 'S', 'H', 'O', 'C1O1', 'C3', 'C', 'H2O1', 'C1S2', 'O2S1', 'C1S1']

HIDDEN = 512
DEPTH = 3
ACTIVATION = 'leaky_relu'
DROPOUT = 0.05
CHECKPOINT_PATH = 'runs_mlp_v10/best.pt'

# Normalization constants (must match training):
TEMP_DIVISOR = 4000
INPUT_LOG_SCALE = 10
ABUND_EPSILON_OFFSET = 12
ABUND_DEX_SCALE = 10
TARGET_ZERO_FLOOR = 1e-30
TARGET_LOG_SCALE = 30
LOG_EPS = 1e-30

def get_activation(name: str) -> nn.Module:
    name = name.lower()
    if name == "relu": return nn.ReLU()
    if name == "gelu": return nn.GELU()
    if name == "tanh": return nn.Tanh()
    if name == "sigmoid": return nn.Sigmoid()
    if name in ("leaky_relu","leakyrelu","lrelu"): return nn.LeakyReLU(negative_slope=1.0e-02)
    raise ValueError(f"Unknown activation: {name}")

class MLP(nn.Module):
    def __init__(self, in_dim: int, out_dim: int, hidden: int, depth: int, activation: str, dropout: float):
        super().__init__()
        act = get_activation(activation)
        layers = []
        last = in_dim
        for _ in range(depth):
            layers += [nn.Linear(last, hidden), act, nn.Dropout(p=dropout)]
            last = hidden
        layers += [nn.Linear(last, out_dim)]
        self.net = nn.Sequential(*layers)
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)

def safe_log10_np(arr: np.ndarray) -> np.ndarray:
    return np.log10(np.clip(arr, LOG_EPS, None))

def _is_abund_col(c: str) -> bool:
    return c.startswith("abund_") and c.endswith("_dex")

def normalize_inputs(df) -> torch.Tensor:
    X = df[INPUT_COLS].copy().to_numpy(dtype=np.float64)
    name_to_idx = {c:i for i,c in enumerate(INPUT_COLS)}
    if "T_K" in name_to_idx:
        X[:, name_to_idx["T_K"]] = X[:, name_to_idx["T_K"]] / TEMP_DIVISOR
    if "P_bar" in name_to_idx:
        X[:, name_to_idx["P_bar"]] = safe_log10_np(X[:, name_to_idx["P_bar"]]) / INPUT_LOG_SCALE
    if "fZ_dex" in name_to_idx:
        X[:, name_to_idx["fZ_dex"]] = X[:, name_to_idx["fZ_dex"]] / INPUT_LOG_SCALE
    if "fZ" in name_to_idx:
        X[:, name_to_idx["fZ"]] = safe_log10_np(X[:, name_to_idx["fZ"]]) / INPUT_LOG_SCALE
    for c,i in name_to_idx.items():
        if _is_abund_col(c):
            X[:, i] = (X[:, i] - ABUND_EPSILON_OFFSET) / ABUND_DEX_SCALE
    return torch.as_tensor(X.astype(np.float32))

def denormalize_targets(y_scaled: np.ndarray) -> np.ndarray:
    # inverse of: y_scaled = log10(max(y, LOG_EPS)) / TARGET_LOG_SCALE
    return np.power(10.0, y_scaled * TARGET_LOG_SCALE)

def load_model(device: str | None = None) -> nn.Module:
    device = torch.device(device) if device else torch.device("cpu")
    in_dim = len(INPUT_COLS); out_dim = len(TARGET_COLS)
    m = MLP(in_dim, out_dim, HIDDEN, DEPTH, ACTIVATION, DROPOUT).to(device)
    ckpt = torch.load(CHECKPOINT_PATH, map_location=device)
    m.load_state_dict(ckpt["model"])
    m.eval()
    return m

if __name__ == "__main__":
    m = load_model()
    print("Loaded MLP with", sum(p.numel() for p in m.parameters()), "parameters")
